[package]
name = "rusty-v8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = "0.41.0"
color-eyre= "0.6.1"
tokio = { version = "1", features = ["full"] }
